USE [master]
GO

/****** Object:  Database [FormularioDocente]    Script Date: 13/04/2019 3:39:58 ******/
CREATE DATABASE [FormularioDocente]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FormularioDocente', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\FormularioDocente.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FormularioDocente_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\FormularioDocente_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FormularioDocente] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FormularioDocente].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FormularioDocente] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FormularioDocente] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FormularioDocente] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FormularioDocente] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FormularioDocente] SET ARITHABORT OFF 
GO

ALTER DATABASE [FormularioDocente] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [FormularioDocente] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FormularioDocente] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FormularioDocente] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FormularioDocente] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FormularioDocente] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FormularioDocente] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FormularioDocente] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FormularioDocente] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FormularioDocente] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FormularioDocente] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FormularioDocente] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FormularioDocente] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FormularioDocente] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FormularioDocente] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FormularioDocente] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FormularioDocente] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FormularioDocente] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FormularioDocente] SET  MULTI_USER 
GO

ALTER DATABASE [FormularioDocente] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FormularioDocente] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FormularioDocente] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FormularioDocente] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FormularioDocente] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FormularioDocente] SET  READ_WRITE 
GO

